image: warehouse_map_keepout_real.pgm
resolution: 0.05
origin: [-5.72, -2.86, 0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.25

# Keepout mask configuration
keepout_filter:
  plugin: nav2_costmap_2d::KeepoutFilter
  enabled: True
  filter_info_topic: /costmap_filter_info