image: warehouse_map.pgm
mode: trinary
resolution: 0.05
origin: [-1.16, -4.39, 0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.25

# Keepout mask configuration
keepout_filter:
  type: keepout_filter
  plugin: nav2_costmap_2d::KeepoutFilter
  enabled: True
  filter_info_topic: /costmap_filter_info
keepout_mask: warehouse_map_keepout_sim_mask.pgm 